---

- name: add or update user password 
  hosts: all

  tasks: 
  - name: change user "george" password 
    user: 
     name: george 
     update_password: always 
     password: "{{ newpassword|password_hash('sha512') }}"
