---

- name: setup apache and open firewalld port 
  hosts: all

  tasks:
  - name: install apache package 
    dnf:
     name: httpd
     state: present 

  - name: start apache 
    service: 
     name: httpd
     state: started

  - name: open http service port in firewalld
    firewalld: 
     serive: http
     permanent: true 
     state: enabled 

  - name: restart firewall service
    service:
     name: firewalld
     state: reloaded 
