---

- name: find a process and kill it 
  hosts: localhost

  tasks:
  - name: get running process from remote host
    ignore_errors: yes
    shell: " ps -ef | grep top | awk ' { print $2 }'"
    register: running_process

  - name: kill running processes
    ignore_errors: yes
    shell: kill "{{ 'item' }}"
    with_items: "{{ running process.stdout_lines }}"

